// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using school_hub.Data;

#nullable disable

namespace school_hub.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("school_hub.Models.Book", b =>
                {
                    b.Property<short>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("BookId"));

                    b.Property<string>("BookPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("LibrarySectionId")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.HasIndex("LibrarySectionId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("school_hub.Models.Exam.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerId"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("school_hub.Models.Exam.Exam", b =>
                {
                    b.Property<short>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("ExamId"));

                    b.Property<TimeOnly>("ExamTime")
                        .HasColumnType("time");

                    b.Property<short>("LessonId")
                        .HasColumnType("smallint");

                    b.Property<byte>("PassingScore")
                        .HasColumnType("tinyint");

                    b.HasKey("ExamId");

                    b.HasIndex("LessonId")
                        .IsUnique();

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("school_hub.Models.Exam.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<short>("ExamId")
                        .HasColumnType("smallint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.HasIndex("ExamId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("school_hub.Models.Exam.StudentAnswer", b =>
                {
                    b.Property<int>("StudentExamId")
                        .HasColumnType("int");

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.HasKey("StudentExamId", "AnswerId");

                    b.HasIndex("AnswerId");

                    b.ToTable("StudentAnswers");
                });

            modelBuilder.Entity("school_hub.Models.Exam.StudentExam", b =>
                {
                    b.Property<int>("StudentExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentExamId"));

                    b.Property<DateOnly>("ExamDate")
                        .HasColumnType("date");

                    b.Property<short>("ExamId")
                        .HasColumnType("smallint");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("TimeToComlete")
                        .HasColumnType("time");

                    b.HasKey("StudentExamId");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentExams");
                });

            modelBuilder.Entity("school_hub.Models.Lesson.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<DateOnly>("CommentDate")
                        .HasColumnType("date");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("UserId");

                    b.HasIndex("VideoId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("school_hub.Models.Lesson.Lesson", b =>
                {
                    b.Property<short>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("LessonId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("ExamId")
                        .HasColumnType("smallint");

                    b.Property<byte>("LessonNo")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("UnitId")
                        .HasColumnType("smallint");

                    b.HasKey("LessonId");

                    b.HasIndex("UnitId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("school_hub.Models.Lesson.Reply", b =>
                {
                    b.Property<int>("ReplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReplyId"));

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ReplyDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReplyId");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("Replys");
                });

            modelBuilder.Entity("school_hub.Models.Lesson.Video", b =>
                {
                    b.Property<int>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VideoId"));

                    b.Property<short>("Duration")
                        .HasColumnType("smallint");

                    b.Property<short>("LessonId")
                        .HasColumnType("smallint");

                    b.Property<string>("VideoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VideoId");

                    b.HasIndex("LessonId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("school_hub.Models.LessonAvailableInSchedule", b =>
                {
                    b.Property<short>("LessonId")
                        .HasColumnType("smallint");

                    b.Property<byte>("ScheduleId")
                        .HasColumnType("tinyint");

                    b.HasKey("LessonId", "ScheduleId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("LessonAvailableInSchedules");
                });

            modelBuilder.Entity("school_hub.Models.Sections.Section", b =>
                {
                    b.Property<short>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("SectionId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("ParentId")
                        .HasColumnType("smallint");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SectionType")
                        .HasColumnType("int");

                    b.HasKey("SectionId");

                    b.HasIndex("ParentId");

                    b.ToTable("Sections");

                    b.HasDiscriminator<int>("SectionType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("school_hub.Models.StudentRating", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<short>("LessonId")
                        .HasColumnType("smallint");

                    b.Property<byte>("RatingValue")
                        .HasColumnType("tinyint");

                    b.HasKey("StudentId", "LessonId");

                    b.HasIndex("LessonId");

                    b.ToTable("StudentRatings");
                });

            modelBuilder.Entity("school_hub.Models.StudentStudyPlan", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<short>("PlanId")
                        .HasColumnType("smallint");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "PlanId");

                    b.HasIndex("PlanId");

                    b.ToTable("StudentSubscriptions");
                });

            modelBuilder.Entity("school_hub.Models.StudentView", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "VideoId");

                    b.HasIndex("VideoId");

                    b.ToTable("StudentViews");
                });

            modelBuilder.Entity("school_hub.Models.StudySchedule", b =>
                {
                    b.Property<byte>("ScheduleId")
                        .HasColumnType("tinyint");

                    b.Property<short>("PlanId")
                        .HasColumnType("smallint");

                    b.HasKey("ScheduleId");

                    b.HasIndex("PlanId")
                        .IsUnique();

                    b.ToTable("StudySchedules");
                });

            modelBuilder.Entity("school_hub.Models.StudyScheduleDetail", b =>
                {
                    b.Property<short>("SubjectId")
                        .HasColumnType("smallint");

                    b.Property<byte>("ScheduleId")
                        .HasColumnType("tinyint");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.HasKey("SubjectId", "ScheduleId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("StudyScheduleDetails");
                });

            modelBuilder.Entity("school_hub.Models.Users.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicturePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasDiscriminator<int>("UserType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("school_hub.Models.Sections.LibrarySection", b =>
                {
                    b.HasBaseType("school_hub.Models.Sections.Section");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("school_hub.Models.Sections.StudyPlan", b =>
                {
                    b.HasBaseType("school_hub.Models.Sections.Section");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("school_hub.Models.Sections.StudySection", b =>
                {
                    b.HasBaseType("school_hub.Models.Sections.Section");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("school_hub.Models.Sections.Subject", b =>
                {
                    b.HasBaseType("school_hub.Models.Sections.Section");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("TotalDuration")
                        .HasColumnType("int");

                    b.HasIndex("TeacherId");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("school_hub.Models.Sections.Unit", b =>
                {
                    b.HasBaseType("school_hub.Models.Sections.Section");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("school_hub.Models.Users.Admin", b =>
                {
                    b.HasBaseType("school_hub.Models.Users.User");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("school_hub.Models.Users.Student", b =>
                {
                    b.HasBaseType("school_hub.Models.Users.User");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("school_hub.Models.Users.Teacher", b =>
                {
                    b.HasBaseType("school_hub.Models.Users.User");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("school_hub.Models.Book", b =>
                {
                    b.HasOne("school_hub.Models.Sections.LibrarySection", "LibrarySection")
                        .WithMany("Books")
                        .HasForeignKey("LibrarySectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibrarySection");
                });

            modelBuilder.Entity("school_hub.Models.Exam.Answer", b =>
                {
                    b.HasOne("school_hub.Models.Exam.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("school_hub.Models.Exam.Exam", b =>
                {
                    b.HasOne("school_hub.Models.Lesson.Lesson", "Lesson")
                        .WithOne("Exam")
                        .HasForeignKey("school_hub.Models.Exam.Exam", "LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("school_hub.Models.Exam.Question", b =>
                {
                    b.HasOne("school_hub.Models.Exam.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("school_hub.Models.Exam.StudentAnswer", b =>
                {
                    b.HasOne("school_hub.Models.Exam.Answer", "Answer")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("school_hub.Models.Exam.StudentExam", "StudentExam")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("StudentExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("StudentExam");
                });

            modelBuilder.Entity("school_hub.Models.Exam.StudentExam", b =>
                {
                    b.HasOne("school_hub.Models.Exam.Exam", "Exam")
                        .WithMany("StudentExams")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("school_hub.Models.Users.Student", "Student")
                        .WithMany("StudentExams")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("school_hub.Models.Lesson.Comment", b =>
                {
                    b.HasOne("school_hub.Models.Users.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("school_hub.Models.Lesson.Video", "Video")
                        .WithMany("Comments")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("school_hub.Models.Lesson.Lesson", b =>
                {
                    b.HasOne("school_hub.Models.Sections.Unit", "Unit")
                        .WithMany("Lessons")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("school_hub.Models.Lesson.Reply", b =>
                {
                    b.HasOne("school_hub.Models.Lesson.Comment", "Comment")
                        .WithMany("Replys")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("school_hub.Models.Users.User", "User")
                        .WithMany("Replys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("school_hub.Models.Lesson.Video", b =>
                {
                    b.HasOne("school_hub.Models.Lesson.Lesson", "Lesson")
                        .WithMany("Videos")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("school_hub.Models.LessonAvailableInSchedule", b =>
                {
                    b.HasOne("school_hub.Models.Lesson.Lesson", "Lesson")
                        .WithMany("LessonAvailableInSchedules")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("school_hub.Models.StudySchedule", "Schedule")
                        .WithMany("LessonAvailableInSchedules")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("school_hub.Models.Sections.Section", b =>
                {
                    b.HasOne("school_hub.Models.Sections.Section", "Parent")
                        .WithMany("Sections")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("school_hub.Models.StudentRating", b =>
                {
                    b.HasOne("school_hub.Models.Lesson.Lesson", "Lesson")
                        .WithMany("Ratings")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("school_hub.Models.Users.Student", "Student")
                        .WithMany("StudentRatings")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("school_hub.Models.StudentStudyPlan", b =>
                {
                    b.HasOne("school_hub.Models.Sections.StudyPlan", "StudyPlan")
                        .WithMany("StudyPlanStudents")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("school_hub.Models.Users.Student", "Student")
                        .WithMany("StudentStudyPlans")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("StudyPlan");
                });

            modelBuilder.Entity("school_hub.Models.StudentView", b =>
                {
                    b.HasOne("school_hub.Models.Users.Student", "Student")
                        .WithMany("StudentViews")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("school_hub.Models.Lesson.Video", "Video")
                        .WithMany("Views")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("school_hub.Models.StudySchedule", b =>
                {
                    b.HasOne("school_hub.Models.Sections.StudyPlan", "StudyPlan")
                        .WithOne("StudySchedule")
                        .HasForeignKey("school_hub.Models.StudySchedule", "PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyPlan");
                });

            modelBuilder.Entity("school_hub.Models.StudyScheduleDetail", b =>
                {
                    b.HasOne("school_hub.Models.StudySchedule", "Schedule")
                        .WithMany("StudyScheduleDetails")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("school_hub.Models.Sections.Subject", "Subject")
                        .WithMany("ScheduleDetails")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("school_hub.Models.Sections.Subject", b =>
                {
                    b.HasOne("school_hub.Models.Users.Teacher", "Teacher")
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("school_hub.Models.Exam.Answer", b =>
                {
                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("school_hub.Models.Exam.Exam", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("StudentExams");
                });

            modelBuilder.Entity("school_hub.Models.Exam.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("school_hub.Models.Exam.StudentExam", b =>
                {
                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("school_hub.Models.Lesson.Comment", b =>
                {
                    b.Navigation("Replys");
                });

            modelBuilder.Entity("school_hub.Models.Lesson.Lesson", b =>
                {
                    b.Navigation("Exam")
                        .IsRequired();

                    b.Navigation("LessonAvailableInSchedules");

                    b.Navigation("Ratings");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("school_hub.Models.Lesson.Video", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("school_hub.Models.Sections.Section", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("school_hub.Models.StudySchedule", b =>
                {
                    b.Navigation("LessonAvailableInSchedules");

                    b.Navigation("StudyScheduleDetails");
                });

            modelBuilder.Entity("school_hub.Models.Users.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Replys");
                });

            modelBuilder.Entity("school_hub.Models.Sections.LibrarySection", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("school_hub.Models.Sections.StudyPlan", b =>
                {
                    b.Navigation("StudyPlanStudents");

                    b.Navigation("StudySchedule")
                        .IsRequired();
                });

            modelBuilder.Entity("school_hub.Models.Sections.Subject", b =>
                {
                    b.Navigation("ScheduleDetails");
                });

            modelBuilder.Entity("school_hub.Models.Sections.Unit", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("school_hub.Models.Users.Student", b =>
                {
                    b.Navigation("StudentExams");

                    b.Navigation("StudentRatings");

                    b.Navigation("StudentStudyPlans");

                    b.Navigation("StudentViews");
                });

            modelBuilder.Entity("school_hub.Models.Users.Teacher", b =>
                {
                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
